# Generated by Django 4.1 on 2022-10-05 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='story_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'jpg', 'jpeg'])]),
        ),
    ]
