# Generated by Django 4.1 on 2022-10-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
